# Generated by Django 4.0.5 on 2022-07-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
