# Generated by Django 4.0.5 on 2022-07-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_name_category_title_rename_name_product_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
