# Generated by Django 4.0.5 on 2022-07-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
