# Generated by Django 4.0.5 on 2022-07-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_comment_photo_product_main_photo_productreview_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_photo',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
